version: "3.2"
services:
    db:
        image: mysql:latest
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: Instituto
            MYSQL_USER: usuario
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        working_dir: /sql
        volumes:
            # Los archivos que están en el docker-entrypoint se ejecutan al iniciar el contenedor
            - ./conf:/etc/mysql/conf.d
            - ./data:/docker-entrypoint-initdb.d
            - persistente:/var/lib/mysql
            # Todos los archivos del repositorio se pondrán en la carpeta app
            - ./sql:/sql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin:latest
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: usuario
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
volumes:
    persistente: